language: python
python:
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt

# blocklist
branches:
  except:
  - testing

# safelist
branches:
  only:
  - master
script:
  - cd main/
  - python3 emailspam.py
  - echo "1"
